version: '3.8'

services:
  backend:
    build: ./ssaverytime-BE
    container_name: ssaverytime-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - ssavery-net

  ai-service:
    build: ./ssaverytime-AI
    container_name: ssaverytime-ai
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - ssavery-net

  prometheus:
    image: prom/prometheus
    container_name: ssaverytime-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - ssavery-net

  grafana:
    image: grafana/grafana
    container_name: ssaverytime-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - ssavery-net

volumes:
  grafana-data:

networks:
  ssavery-net:
    driver: bridge